### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by avhm** [xnimorz/svelte-input-mask#1]
This doesn't appear to be working on Android Oreo Chrome in one case, I can't seem to replicate in the emulators.

The demo at https://xurgr.csb.app doesn't work, input fields remain static, and are not updated. Any ideas?

**Comment by xnimorz** [comment]
Hello, thank you for the issue. 
Could you specify the version of chrome, please?

**Comment by xnimorz** [comment]
@AnthonyMann I've fixed the issue and published `svelte-input-mask@0.0.2`
I've tested this demo https://xurgr.csb.app/ on nexus 5. 

Feel free to reopen the issue or write to me if you still have problems with android
