### ISSUE TITLE
Way to get "raw" value

### ISSUE THREAD

**Issue by Miaourt** [xnimorz/svelte-input-mask#2]
Hello !
First, thanks for this, it's working great.
I wondered if there is a way to get the "unmasked" value ? Right now, I only have access to "masked" and "visible" value.

**Comment by xnimorz** [comment]
Hi, 
Thank you for the feedback!
Yes, you can't get unmasked value at the moment. And it would be good to provide it. 
I think I can add this to the lib within 5-7 days (when I'll have some free time)

**Comment by Miaourt** [comment]
Awesome, it's not really urgent on my side, so if you're really busy take it easy, but this would be a really nice addition for plenty of cases 👍

**Comment by Miaourt** [comment]
Hi hi, sorry for digging it up, I might need it more soon that expected ^^' if you happen to have a bit more time

**Comment by xnimorz** [comment]
Hi, @Miaourt 
Published in `svelte-input-mask@0.0.3`

Here you can find the example of unmaskedValue usage: https://github.com/xnimorz/svelte-input-mask/blob/master/example/ManagableValue.svelte#L4-L17

**Comment by Miaourt** [comment]
Lovely, will test this tomorrow (CET)!

**Comment by Miaourt** [comment]
```
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
node_modules/svelte-input-mask/MaskInput.svelte (96:13)
94:       window.webkitRequestAnimationFrame ||
95:       window.mozRequestAnimationFrame ||
96:       (fn => setTimeout(fn, 0));
                 ^
97:     // For android
98:     raf(() => inputEl.setSelectionRange(start, end));
```
I'm getting this error at build

EDIT : ok, nothing to do with svelte-input, it's an issue with svelte 3.17.2, it work perfectly ! :)
