### ISSUE TITLE
Alphabets masking

### ISSUE THREAD

**Issue by pravnkay** [xnimorz/svelte-input-mask#23]
Hi, new to svelte and found this awesome package.
Firstly, It works wonderfully and thanks for that.

My need is that, I don't see any ways to mask alphabets input in a string.

For ex: I have a string in the format, 
XXXX-XX-00-0000
where
X - Alphabets
0 - Numerals

Can this be added to the package ? or am I missing something ?

**Comment by xnimorz** [comment]
Hey @pravnkay 

Please, see https://codesandbox.io/p/sandbox/svelte-mask-input-demo-xurgr?file=%2FMixed.svelte example with Mixed format

It can be done by using https://github.com/xnimorz/svelte-input-mask?tab=readme-ov-file#which-props-it-has maskFormat property which by default supports alphabetic symbols and numbers: https://github.com/xnimorz/masked-input/blob/master/packages/input-core/src/index.ts#L16-L28

You also can define your own symbols
