### ISSUE TITLE
I cant use class directive in input

### ISSUE THREAD

**Issue by bonomiandreia** [xnimorz/svelte-input-mask#5]
Hello everyone! I came to report an error, when I use class directive like
`<input class="{errors != '' || errors.name != '' ? 'active' : ''}" type="text"/>`, The class directive doesn't work. Would be a something to improve in project. 

Thank you. =]

**Comment by xnimorz** [comment]
Hi @bonomiandreia
Thank you for the issue, I'll take a look at the problem on the next week and write back to you

**Comment by xnimorz** [comment]
Hello @bonomiandreia !
I've checked the problem and fixed it. 

I've published `svelte-input-mask@1.0.0` but the only thing why it's a major release that's I used `$$restProps` variable which is supported only from `svelte@3.20.x`

Thank you for the issue!

**Comment by xnimorz** [comment]
I'm going to close this issue as it seems, the problem was solved
Feel free to reopen it in case you're still having a problem
