### ISSUE TITLE
Demo and Example not working

### ISSUE THREAD

**Issue by spsaucier-bakkt** [xnimorz/svelte-input-mask#6]
No inputs seem to be working here: https://codesandbox.io/s/romantic-franklin-xurgr

And when I try to use `<NumberFormat />` in my project, it returns a 500 error: `value.replace is not a function`

**Comment by xnimorz** [comment]
Hi @spsaucier-bakkt 
I've just updated the example. Now it uses svelte 3.20.x version and the version of svelte-input-mask is 1.0.0.

In case you are still experiencing any problems with svelte-input-mask, provide some logs or an example, please. 
Also, the project was updated a day ago, and now peer dependency is `svelte >= 3.20.0`

**Comment by spsaucier-bakkt** [comment]
Thanks for improving the demo. There's still an issue with `<NumberInput />`, however: `value.filter is not a function` when anything is typed into it.

**Comment by xnimorz** [comment]
Hi @spsaucier-bakkt 
Sorry for the long response, 
I missed the second part of the problem. 
I've published 1.0.1 version so that NumberInput should work properly.

**Comment by xnimorz** [comment]
I'm going to close this issue as it seems, the problem was solved
Feel free to reopen it in case you're still having a problem
